### PR TITLE
added RunCommand

### PR DESCRIPTION
**Pull request by lolbinarycat**

### CODE REVIEW

**Comment by 200sc** [comment]
Changed to merged into develop per contributing guidelines

**Comment by Implausiblyfun** [comment]
I dont love this function and the usage of it  seems a bit odd but fine.

**Comment by lolbinarycat** [comment]
Sorry, I meant to submit it on develop.

**Comment by lolbinarycat** [comment]
Another use is if you wanted to implement an in-game developer console instead of using stdin

**Comment by lolbinarycat** [comment]
Oops, Apparently I can't read.

**Pull request merged**
