### PR TITLE
Release/3.0.0 Beta 1

### PR DESCRIPTION
**Pull request by 200sc**
Changelog pending

Considering this as beta 1. See the 3.0.0 project https://github.com/oakmound/oak/projects/2 for notes and issues to be addressed in beta 2, currently anticipated to be the last prerelease of 3.0.0

### CODE REVIEW

**Comment by 200sc** [comment]
Want to fix a problem with particle lifespans before merging.

**Review by 200sc — COMMENTED** [review]
Reviewed. Changelog:

Oak v3.0.0-beta1 changelog

general
- reduced verbosity of all libraries
    unnecessary logs have been removed throughout the codebase
- Several functions which previously logged or ignored errors now return them

audio
- 200sc/klangsynthese is now effectively vendored locally.
    this change is primarily intended to speed up development iteration when 
    working on these dependencies and to make version pinning more straightforward
- channels, signals, and channel managers have been removed. They were tricky to 
    use correctly and designed toward a specific game, not used by any games
    since

collision
- Added `PhaseCollisionWithBus`
- Moved `CallOnHits` to be a method on a `Tree`
- `ReactiveSpace` can now take in a `Tree`, and its methods are concurrent safe
- `NewEmptyReactiveSpace` has been removed
- `CID` is now `IDTypeCID`
- `PID` is now `IDTypePID`
- `Space.String()` has been removed
- `Space.SetZLayer(float64)` has been added

debugstream
- A new package that contains utilities for adding command line debug commands. 
    Not intended to be a full-fledged CLI builder, just enough for some helper
    tools. 

dlog
- `SetDebugFilter` has been renamed `SetFilter`
- filter strings are now `func(string) bool`, instead of picking between regex matching and containment.
- `Warn` has been removed 
- `SetLogger` has been removed
- Exposed `DefaultLogger`, setting this replaces `SetLogger`
- `Logger` and `FullLogger` interfaces are now combined
- `CreateLogFile` has been removed
- `SetDebugLevel` has been renamed `SetLogLevel`
- `FileWrite` has been removed
- `SetOutput` has been added, replacing `FileWrite` and `CreateLogFile` 

entities
- Removed `String` methods from all entities

entities/x/btn
- Added `Destroy` to `Btn`
- `DisallowRevert` is now flipped to `AllowRevert`

entities/x/force
- Now accepts `*scene.Context`s

entities/x/shake
- New package from oak/shake.go, can generically shake screens + anything

event 
- `Bus.ResolvePending` has been renamed to `Bus.ResolveChanges`
- event Busses now take a `CallerMap` reference
- `Enter` events now take an `EnterPayload`, containing total frames, time since
    last frame, and proportionally how that time compares to the expected 
    average tick time
- Added `TriggerCIDBack`

examples
- New example `click-propagation` demoing mouse click layers
- New example `clipboard`, using `github.com/atotto/clipboard`
- New example `svg` demonstrates using svg helper libraries
- `fallback-font` has its dependencies in its own go module
- `joystick-viz` now demonstrates joystick deadzones
- `top-down-shooter` part 6 has been modified to use new event enter frame 
    details and `DoBetweenDraws`
- Removed `cliffracers` example

joystick
- Stick changes can be isolated to only propagate if they exceed a deadzone
    threshold


mouse 
- Mouse bindings now take in a `(*mouse.Event)` instead of a `(mouse.Event)`
- `Event` now has a `StopPropagation` boolean which, when set, will stop mouse
    collision spaces beneath the one triggered on from receiving the event. 
- Mouse gestures, unused, have been removed, for now.


oak
- Added `SkipRNGSeed` to `Config`, a setting which will skip calling `math/rand.Seed` if set. 
- debug console functionality has been moved to debugstream
- the default controller is now lazily initialized
- `Controller`s have been renamed to `Window`s
- Added `Window.DoBetweenDraws`, which will confine a function to be called
    in between screen draws. 
- `Joystick` is now `InputTypeJoystick`
- `KeyboardMouse` is now `InputTypeKeyboardMouse`
- `trackInputChanges` now propagates `InputChange` events 
- the engine will more reliably exit with a clean error if it cannot proceed
    during initialization
- `Shake` functionaltiy has moved to `entities/x/shake`

oakerr
- Language constants now match ISO 639-1

render
- `NewStrText` is now `NewText`, the old `NewText` now `NewStringerText`
- Added `ToSprite` to `CompositeR`
- Removed `DrawForTime` (see scene context)
- Removed draw polygons
- DrawToScreen now accepts a *intgeom.Point2 for the viewport position
- Removed `FontManager`

render/particle
- Allocators can now be stopped

scene
- Added `DoAfter`, `DoAfterContext`, and `DrawForTime` to `Context`

shiny
- `noop` build tag has been renamed `nooswindow`
- Added `GetCursorPos` to windows/osx
- Fixed bug where closed windows would stop oak, but not actually close the
    window on linux
- Fixed potential race on window intialization on linux

timing
- Removed `DynamicTicker`, built in `*time.Ticker`s support our use of these since Go 1.15.
- Removed `DoAfter` and `DoAfterContext`, moved to scene package

**Comment by 200sc** [comment]
Per above changelog:

This release resolves #4 
This release resolves #153

**Comment by 200sc** [comment]
@Implausiblyfun Look good?

**Review by Implausiblyfun — APPROVED** [review]
Sorry it took me a while to get to this. As far as I can tell things are in  a pretty good state. 

As 3.0 comes to a head one thing to consider is pulling out a migration doc from the changelogs. In general the running an existing program does indicate the changes needed but it may be nice to pull things out to a general guide. (looking at the signature change for text).

**Pull request merged**
