### PR TITLE
Release/2.3.0

### PR DESCRIPTION
**Pull request by 200sc**
Oak 2.3.0

Big feature points: joystick support, removed dependency for linux audio

Todo: new Readme
Todo: Changelog

### CODE REVIEW

**Comment by Implausiblyfun** [comment]
2.3.0 Changelog:

`Overall`:
- Improved test coverage
- Updated example READMEs

`alg`:
- Added standard direction helpers
- Allow usage of a rand other than the default rand


`Collision`:
- Minor refactoring

`oak`: 
- Added new screen controls
- New debug commands

`joystick`: 
- Joystick support added

`render`: 
- Add some missing methods

**Comment by 200sc** [comment]
Note to self: check for the debug rtree

**Comment by 200sc** [comment]
Credit Renee French for the gopher in sprite demo

**Comment by 200sc** [comment]
For next release: 

Stabilize debug rtree
Mac testing
Selector from weekly87 into btn

**Pull request merged**
