### PR TITLE
Feature/audio overhaul

### PR DESCRIPTION
**Pull request by 200sc**
See #189, and also #131, although the latter is not done yet

Before this is merged, the new audio system should have implementations for (or spiked and failed for):
- [x] windows
- [x] darwin 
- [x] linux
- [ ] js 
- [ ] android

### CODE REVIEW

**Comment by 200sc** [comment]
Linux is working with two needed things
- go mod tidy
- investigate this: 
image
The top left pixel there indicates the audio we're writing for triangle waves (and I believe sin waves) (and maybe just for 32 bit) is problematic. On linux this appears via lower pitched sin and triangle waves being quieter than upper pitches, where pulse and sin do not have this condition.

**Comment by 200sc** [comment]
JS has been spiked and it looks like one needs to use AudioWorklets (https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletNode) to handle audio like we want to, with a streaming interface. The instructions for doing this revolve around having multiple js files that load each other as classes, which I don't know how to do with syscall/js, if it's even possible.

**Comment by 200sc** [comment]
Darwin can also use our pulse implementation (or our jfreymuth/pulse wrapper, to be less generous)-- and personally I prefer that requirement to the other roads one would need to go down, i.e. compiling more C / C variants to interact with osx specific audio libraries.

**Comment by 200sc** [comment]
Current thought is to do:
1. Install pulse on the linux arm box and adjust the non-arm test suite to skip examples (they are more effectively  tested by graphical runners) 
2.  Expose a choice of which audio backing you want to use (with the current options being pulse for unix and direct sound for 
3. Change the old and new direct sound audio systems to share a device so they can both be compiled in
4. Maybe try to expose to the api a choice of output sound device? Might be too early for that. 

Then merge this in and cut a minor release bump for it.

**Comment by 200sc** [comment]
(JS audio can't follow this API as syscall js currently works and android audio basically only works with OpenAL by my understanding, both of which are worth working on but neither worth holding back this branch).

**Comment by Implausiblyfun** [comment]
Other than the todo with the early return the only other thing of note that I see is the unlimited draw rate change.
Namely can we just add it to the description so we dont miss it during changelog creation?

**Comment by 200sc** [comment]
Changelog:
- Adds a streaming audio API under `audio/pcm`, with direct sound support on windows and pulse audio support on osx/linux. 
- Adds a piano example to test and demonstrate the `pcm` interface. 
- Adds additional key handling to JS (Shift and Delete)
- Adds a `UnlimitedDrawRate` configuration option which will cause the draw loop to not wait at all between draw frames. This setting is, experientially, particularly useful on WIndows, where a frame rate of 60fps is high enough that it exceeds Window's default timer precision and will result in inconsistent frame times.

**Comment by 200sc** [comment]
Issues to open after this is merged and released:
- Support listing and selecting a specific audio device to play audio on 
- Support consuming audio input (e.g. midi controllers or microphones)
- Support more audio APIs on windows (XAudio2)
- Support more audio APIs on Linux (ALSA)
- Support more audio APIs on OSX (IOKit)
- Support OpenAL (for Android specifically but for all OSes)
- Support explicitly non-streaming audio for JS in the new PCM package
- OakV4: combine audio packages

Or maybe this is just a "big audio overhaul" issue with these points as sub goals?

**Comment by 200sc** [comment]
@Implausiblyfun Objection to merging this and cutting oak 3.4.0?

**Pull request merged**
